# Generated by Django 5.2 on 2025-05-02 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='name',
            new_name='title',
        ),
    ]
